# rails_service.yml
apiVersion: v1
kind: Service
metadata:
  name: rails
spec:
  selector:
    app: rails
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000 # You can choose a port between 30000-32767
  type: NodePort
