# rails-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rails
spec:
  selector:
    app: rails
  ports:
    - protocol: TCP
      port: 3000 # Port exposed internally in the cluster
      targetPort: 3000 # Port your Rails container listens on
  type: ClusterIP
