apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image
spec:
  steps:
    - name: build
      image: docker
      script: |
        docker build -t <dockerhub-user>/rails-app:latest .  
        docker push <dockerhub-user>/rails-app:latest
